export const AUTH_SUCCESS = 'auth_success';
export const AUTH_FAIL = 'auth_fail';
export const LANGUAGE_CHANGE = 'language_change';

export const HOME_REQUEST_FEEDBACK = 'HOME_REQUEST_FEEDBACK'
export const HOME_RECEIVE_FEEDBACK = 'HOME_RECEIVE_FEEDBACK'
export const RECEIVE_ERROR_HOME = 'RECEIVE_ERROR_HOME'

export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN'
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP'
export const RECEIVE_SIGN_UP = 'RECEIVE_SIGN_UP'
export const REQUEST_ABOUT_US = 'REQUEST_ABOUT_US'
export const RECEIVE_ABOUT_US = 'RECEIVE_ABOUT_US'
export const REQUEST_ASSIGN_STORAGE_USER = 'REQUEST_ASSIGN_STORAGE_USER'
export const RECEIVE_ERROR_LOGIN = 'RECEIVE_ERROR_LOGIN'
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'

export const REQUEST_FEEDBACK = 'REQUEST_FEEDBACK'
export const RECEIVE_FEEDBACK = 'RECEIVE_FEEDBACK'

export const REQUEST_USER = 'REQUEST_USER'
export const RECEIVE_USER = 'RECEIVE_USER'
export const UPDATE_USER = 'UPDATE_USER'


export const REQUEST_ADD_OTHER_USER = 'REQUEST_ADD_OTHER_USER'
export const RECEIVE_ADD_OTHER_USER = 'RECEIVE_ADD_OTHER_USER'


export const REQUEST_PATIENT_LIST = 'REQUEST_PATIENT_LIST'
export const RECEIVE_PATIENT_LIST = 'RECEIVE_PATIENT_LIST'

export const REQUEST_FORGOT_PASS = 'REQUEST_FORGOT_PASS'
export const RECEIVE_FORGOT_PASS = 'RECEIVE_FORGOT_PASS'

export const REQUEST_CHANGE_PASSWORD = 'REQUEST_CHANGE_PASSWORD'
export const RECEIVE_CHANGE_PASSWORD = 'RECEIVE_CHANGE_PASSWORD'
export const REQUEST_CHANGE_PASSWORD_CLEAR = 'REQUEST_CHANGE_PASSWORD_CLEAR'




